print(sorted([
    "LR- 2D & 3D",
    "LR- Arrangement",
    "DI- Charts",
    "LR- Coins and Weights",
    "DI- Miscellaneous",
    "DI- DI with connected data sets",
    "DI- Data Interpretation",
    "DI- Data change over a period",
    "LR-Games and Tournaments",
    "DI- Maxima-Minima",
    "LR- Miscellaneous LR",
    "LR- Puzzles",
    "DI- Quant Based DI",
    "LR- Quant Based LR",
    "LR- Scheduling",
    "LR- Selection With Condition",
    "Set Selection",
    "DI- Special Charts",
    "DI- Table based DI Sets",
    "LR-Truth Lie Concept",
    "DI- Venn Diagrams",
]))
